[app]
full_screen = false

[video]
video_url = "http://192.168.0.146:8080/raw"
frame_width = 1920
frame_height = 1088
fps = 15
crop_x = 605
crop_y = 297
crop_width = 605
crop_height = 517

[capture]
save_capture = true
save_root = "/tmp/records"

[dummy]
use_dummy = false
dummy_root = "./data/capture/20250816_100250"
dummy_frames = "data_dummy/dummy_frames.txt"
dummy_path = "data_dummy/dummy_path.txt"
