[app]
full_screen = false
# splash = "./images/logo.png"

[video]
video_url = "http://192.168.0.39:8080/raw"
frame_width = 1920
frame_height = 1088
fps = 10
crop_x = 652
crop_y = 438
crop_width = 318
crop_height = 306

[capture]
save_capture = false
save_root = "/tmp/records"

[dummy]
use_dummy = false
dummy_root = "./data/capture/20250816_100250"
dummy_frames = "data_dummy/dummy_frames.txt"
dummy_path = "data_dummy/dummy_path.txt"
