[app]
full_screen = true
show_result = false
overlay_x = 1192
overlay_y = 14
overlay_width = 400
overlay_height = 400

[video]
video_url = "http://localhost:8080/raw"
frame_width = 1920
frame_height = 1088
fps = 1
crop_x = 651
crop_y = 357
crop_width = 599
crop_height = 367

[capture]
save_capture = false
save_root = "/tmp/records"

[dummy]
use_dummy = false
dummy_root = "./data/capture/20250816_100250"
dummy_frames = "data_dummy/dummy_frames.txt"
dummy_path = "data_dummy/dummy_path.txt"
